### ISSUE TITLE
ValidateRemoteCertificate returns false with "Trusted" self-signed certificates

### ISSUE THREAD

**Issue by igarciaolaizola** [kerryjiang/SuperSocket.ClientEngine#10]
Conditions:
- The client is connecting to a Websocket server that uses a self-signed certificate.
- The client has enabled AllowUntrustedCertificate flag.
- The client has added the certificate to its Trusted Root Certificates store.

Result:
- ValidateRemoteCertificate will return false because sslPolicyErrors does not contain RemoteCertificateChainErrors but contains a RemoteCertificateNameMismatch error.
- If we remove the certificate from the client's Trusted Root Certificate store, ValidateRemoteCertificate will return true (sslPolicyErrors will contain both RemoteCertificateChainErrors and RemoteCertificateNameMismatch).

This is not the typical scenario. However, it does not feel right to throw an invalid certificate error just because the client has decided that the certificate should be trusted (adding it to the Trusted Root Certificate store).

Link to ValidateRemoteCertificate: https://github.com/kerryjiang/SuperSocket.ClientEngine/blob/master/Core/SslStreamTcpSession.cs#L165

**Comment by kerryjiang** [comment]
From the code, websocket4net only allow it in the DEBUG mode.

**Comment by kerryjiang** [comment]
I think the self-signed certificate should be created with the CN which is same with the websocket request host.

**Comment by igarciaolaizola** [comment]
I have already created the certificate with a CN that matches the Websocket request host, but still getting the RemoteCertificateNameMismatch. However, I think that the reason for this RemoteCertificateNameMismatch is not the issue here. The problem is that the same certificate will be valid only if the client has not added it to his Trusted Root Certificates store (what makes no sense to me).

**Comment by kerryjiang** [comment]
The error RemoteCertificateNameMismatch means that you requested use a host which is not same with the certificate's CN.

Could you tell me your certificate's CN and how you connect the server from the client?

**Comment by igarciaolaizola** [comment]
My certificate has the following data:
- Issuer:
 - O = My Enterprise S.L. (selfsigned)
 - CN = SERVER001
- Subject:
 - O = My Enterprise S.L. (selfsigned)
 - CN = SERVER001

The Websocket connection string I am using is the following one:
- wss://SERVER001:8102/App/5d04f035-4f59-459e-8c2c-e5c98bb82a08

The CN and hostname are the same. However, I insist, the RemoteCertificateNameMismatch of the certificate is not what I am complaining about. This behavior is what I am talking about:
- RemoteCertificateNameMismatch + RemoteCertificateChainErrors + AllowUntrustedCertificate = Certificate OK
- RemoteCertificateNameMismatch + AllowUntrustedCertificate = Certificate Error

**Comment by kerryjiang** [comment]
Ok, i'll check this issue again!

**Comment by kerryjiang** [comment]
For a temporary work around, you can register a callback using the statement below:
ServicePointManager.ServerCertificateValidationCallback += xxx

**Comment by igarciaolaizola** [comment]
I was already using a custom callback as a workaround, but I've thought it was a good idea to report the issue. Thanks! ;)

**Comment by kerryjiang** [comment]
I did a fix, could you take a look?

**Comment by igarciaolaizola** [comment]
Your fix seems right: d94d01c7af37bf8e18dd283298b306492e78ea3e
I will know investigate why my self-signed certificate is giving me a RemoteCertificateNameMismatch error.

**Comment by AmitDiwan012** [comment]
hi kerry ! please provide sample example of "ServicePointManager.ServerCertificateValidationCallback".
