### ISSUE TITLE
缺少一个supersocket.ProtoBase引用

### ISSUE THREAD

**Issue by lsysunbow** [kerryjiang/SuperSocket.ClientEngine#16]
看到代码中缺少一个supersocket.ProtoBase的引用，是否能提供一个呢，初学者，请不吝赐教 谢谢

**Comment by kerryjiang** [comment]
Hello, 请使用nuget还原引用包。

**Comment by kerryjiang** [comment]
另，ClientEngine不依赖于supersocket.SocketBase
