### ISSUE TITLE
m_ConnectTaskSource空引用

### ISSUE THREAD

**Issue by jonney-wang** [kerryjiang/SuperSocket.ClientEngine#17]
EasyClientBase在关闭时，或开启多个异步连接时，会提示”m_ConnectTaskSource空引用“
最后只能将EasyClientBase里的两句//m_ConnectTaskSource = null;注释掉，托管平台应该可以自动回收吧。
背景：
自己写继承类SuperSocketClient:EasyClient时，想客户端自动重连服务器，不管什么情况下断开，添加新方法：
public Task<bool> Connect(IPEndPoint ipEndPoint)
        {
            if (!IsConnected)
            {
                ServerAddress = ipEndPoint;
                Task<bool> result = ConnectAsync(ipEndPoint);
                if (!result.Result)
                {
                    Reconnect();
                }
                return result;
            }
            return null;
        }

private void Reconnect()
        {
            if (this.AutoReconnect == TimeSpan.Zero)
            {
                return;
            }

            Action<bool> action = (connected) =>
            {
                if (connected == false)
                {
                    Thread.Sleep((int)this.AutoReconnect.TotalMilliseconds);
                    Reconnect();
                }
            };

            ConnectAsync(ServerAddress).ContinueWith((t) => action(t.Result));
        }

**Comment by kerryjiang** [comment]
我怀疑你的客户端代码可能有问题，对同一client并发调用了多次Connect方法。

**Comment by kerryjiang** [comment]
你的自动重连实现可能有问题。

**Comment by jonney-wang** [comment]
不好意思，原来我是在连接发生异常时，再次异步连接，这种情况下会发生多个异步连接，但是后来想了这种方式是不对的。可能发生异常的地方难以估计，最后在连接关闭的事件里添加了再次连接的方法， m_ConnectTaskSource=null不需要注释。
现在我请问：在连接关闭的事件里添加了再次请求异步连接，这种方式是否合理？是否会出现连接关闭了，但是没有引发关闭事件（目前还没测试出这样的情况）？是否有更好的方式？
按照我现在的方式，有一个问题请看截图：（这种情况发生在，我把WIFI连接关闭，没有连接任何网络，但是网卡是可用状态）

最后还有个地方我修改了，，原来是private，因为使用客户端引擎，一般会继承EasyClient，然后实现自己的一些方法，如果捕捉到异常，当然希望能触发EasyClient的Error事件，自然private不大合适。

以上请了解，谢谢了



jonney_wang@163.com
 
发件人： Kerry Jiang
发送时间： 2015-12-21 19:33
收件人： kerryjiang/SuperSocket.ClientEngine
抄送： jonney-wang
主题： Re: [SuperSocket.ClientEngine] m_ConnectTaskSource空引用 (#17)
我怀疑你的客户端代码可能有问题，对同一client并发调用了多次Connect方法。

**Comment by kerryjiang** [comment]
1) 连接上之后断开必然会触发OnClosed事件;
2) 没有连接上的时候尝试连接失败，可能只会触发OnError事件;
3) 任何修改，请你在fork之后的代码库里进行，然后 send pull request.
