### ISSUE TITLE
m_ConnectTaskSource.SetResult时报错

### ISSUE THREAD

**Issue by jonney-wang** [kerryjiang/SuperSocket.ClientEngine#18]
m_ConnectTaskSource.SetResult时报错，提示此任务已经结束了，不能再赋值。
我只能修改了源码：
if (!m_ConnectTaskSource.Task.IsCompleted)
                {
                    m_ConnectTaskSource.SetResult(false/true);
                }

**Comment by kerryjiang** [comment]
This issue had been fixed already.
