### ISSUE TITLE
ReadMe的添加需要使用NuGet

### ISSUE THREAD

**Issue by chucklu** [kerryjiang/SuperSocket.ClientEngine#23]
好多人，不知道这个项目依赖的dll，需要通过NuGet来获取

**Comment by kerryjiang** [comment]
Ok, 我这边是编译的时候自动下载的。
SuperSocket.ClientEngine近期会发布一个版本，希望能有时间弄一下readme和文档。

**Comment by kerryjiang** [comment]
Added this point in the read me.
