### ISSUE TITLE
how to use commandbase in client?

### ISSUE THREAD

**Issue by askdong** [kerryjiang/SuperSocket.ClientEngine#24]
Dear Jiang,

我们知道在服务器端我们可以使用如下类似的class来识别协议里面的关键字
public class ECHO : StringCommandBase<TestSession>

但是在client端，同样需要识别来自服务端的消息，如何构建commandbase，没有appsession呀！

感谢！

**Comment by kerryjiang** [comment]
EasyClient暂无直接这样的支持，但是你可以自己做个Command的switch(参考WebSocket4Net).
在客户端我倾向于更简单的解决方案。

**Comment by askdong** [comment]
多谢回复！
