### ISSUE TITLE
EasyClient not working with SSL

### ISSUE THREAD

**Issue by sandvest** [kerryjiang/SuperSocket.ClientEngine#25]
Hi,
The HostName in TcpClientSession is not set from EasyClientBase(was earlier set in constructor). 

The function OnGetSocket(SocketAsyncEventArgs) in SslStreamTcpSession fails because the HostName is not set. ( sslStream.BeginAuthenticateAsClient(HostName, securityOption.Certificates, securityOption.EnabledSslProtocols, false, OnAuthenticated, sslStream); )

Atle

**Comment by kerryjiang** [comment]
Thanks for finding that..
I was aware of it but it still was missed :)

I'll try to fix it asap.

**Comment by atleborg** [comment]
Thanks, the AllowUnstrustedCertificate and NoDeplay must also be configurable from EasySocket if security is set to SSL/TLS.

**Comment by kerryjiang** [comment]
I made a serials of changes just now. Should cover what you said already.
