### ISSUE TITLE
Building with netstandard

### ISSUE THREAD

**Issue by skaa** [kerryjiang/SuperSocket.ClientEngine#45]
When building project targeted netstandard1.6 (or 1.3) with reference `"WebSocket4Net": "0.15.0-beta6"` getting error:
`The type 'ConcurrentQueue<T>' exists in both 'SuperSocket.ClientEngine, Version=0.8.0.6, Culture=neutral, PublicKeyToken=null' and 'System.Collections.Concurrent, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`
You can add line
`"../Core/ConcurrentQueue.cs"`
to `excludeFiles` section and
`"NETStandard.Library": "1.3.0",`
to `dependencies` section.

**Comment by kerryjiang** [comment]
Great finding!

If so, I can use "'System.Collections.Concurrent, Version=4.0.10.0" instead.

**Comment by kerryjiang** [comment]
Dix a fix just now.

https://github.com/kerryjiang/SuperSocket.ClientEngine/commit/a4854170d90721cc0c43c4aced0d6b4d3e864a3f
