### ISSUE TITLE
How to open multiple connections

### ISSUE THREAD

**Issue by christopher3683** [kerryjiang/SuperSocket.ClientEngine#48]
Hi,

How to open multiple connections with easy client

**Comment by kerryjiang** [comment]
Just instantialize multiple clients, it doesn't work?

**Comment by christopher3683** [comment]
Thanks for your reply,

How to maintain session for multiple clients

**Comment by kerryjiang** [comment]
Sorry, I cannot understand your question.

What do you mean maintain?
