### ISSUE TITLE
Azure WebApp - SocketException (0x80004005)

### ISSUE THREAD

**Issue by schappel** [kerryjiang/SuperSocket.ClientEngine#49]
Receiving the following error when running inside an Azure WebApp:
`System.Net.Sockets.SocketException (0x80004005): An address incompatible with the requested protocol was used`
I have a pull request coming to work around this issue.

**Comment by kerryjiang** [comment]
Fixed.
https://github.com/kerryjiang/SuperSocket.ClientEngine/pull/50
