### ISSUE TITLE
SuperSocket.ClientEngine-master\Common\ConcurrentBatchQueue 的  TryDequeue BUG

### ISSUE THREAD

**Issue by yusliao** [kerryjiang/SuperSocket.ClientEngine#53]
源码：
while (true)
            {
                var item = array[i];

                while (m_NullValidator(item))
                {
                    spinWait.SpinOnce();  /// 这里会出现死循环  ，应该先 i++ ；
                    item = array[i];
                }

                outputItems.Add(item);
                array[i] = m_Null;

                if (entity.Count <= (i + 1))
                    break;

                i++;
            }

**Comment by kerryjiang** [comment]
你好，此处不是死循环，是等待数组上该位置被放置对象。

**Comment by yusliao** [comment]
哦，谢谢解答，代码看的不够仔细，打扰您了，我再多看看。
