### ISSUE TITLE
SuperSocket.ProtoBase v1.7.0.14, Func<> and Action<> errors.

### ISSUE THREAD

**Issue by DamienLaw** [kerryjiang/SuperSocket.ClientEngine#58]
After I updated my project to the latest SuperSocket.ProtoBase v1.7.0.14 through NuGet, I'm beginning to get

> The type 'Func<TResult>' exists in both 'SuperSocket.ProtoBase' and 'mscorlib'

I'm using both `System.Func<>` and `System.Action<>` and they are now throwing errors because SuperSocket.ProtoBase now apparently has also the same type with the same namespace.

**Comment by kerryjiang** [comment]
Which framework of SuperSocket.ProtoBase do you use?

.NET 2.0?

**Comment by DamienLaw** [comment]
I didn't really specify the .NET framework of SuperSocket.ProtoBase that I use.
Just update from the previous version1.7.0.13 through NuGet. However, from what I can see, it is listed on the NuGet package that one of the dependencies are **.NETStandard,Version=1.1**

My project is using .NET 4.6.2 if that helps. Thanks.

**Comment by ishowfun** [comment]
I Got the same problem.
And something more:
The "Build.bat" didn't work and showed the error:Can't find path.
I modified the MSBuild path as same with SuperSocket's.
Then it worked ,but build failed  when it building with the project  SuperSocket.ClientEngine.SL40.csproj.
Please seperate the buildings with these projects so we can build only which we want.Many Thx!

**Comment by kerryjiang** [comment]
Finally fixed the issue. The reason is I packed .net 2.0's assembly of SuperSocket.ProtoBase as .net core one by mistake.

Now you can get the latest source code and make a build.

@ishowfun Please choose a solution file or project file to build for now.
