### ISSUE TITLE
SuperSocket.ClientEngine is conflicting with System.Collections.Concurrent.ConcurrentQueue<>

### ISSUE THREAD

**Issue by berdon** [kerryjiang/SuperSocket.ClientEngine#61]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'ConcurrentQueue<T>' exists in both 'SuperSocket.ClientEngine, Version=0.8.0.6, Culture=neutral, PublicKeyToken=null' and 'System.Collections.Concurrent, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Comment by kerryjiang** [comment]
Could you try 0.8.0.8?

**Comment by berdon** [comment]
This actually stems from using WebSocket4Net v0.15.0-beta6 - which seems to
rely on the 0.8.0.6. Is there a newer version or could you bump that to
0.8.0.8?


Regards,
*Austin Hanson*

**Comment by berdon** [comment]
Additionally, "ExtensionsAttribute" is also conflicting. I'm not sure if that is fixed in 0.8.0.8.
