### ISSUE TITLE
Send方法不支持ArraySegment的Offset属性

### ISSUE THREAD

**Issue by fish0413** [kerryjiang/SuperSocket.ClientEngine#65]
请修改AsyncTcpSession.cs文件的第170行，原代码不支持Offset属性

m_SocketEventArgsSend.SetBuffer(currentItem.Array, 0, currentItem.Count);

**Comment by kerryjiang** [comment]
Thanks, nice finding!
I have did a fix just now.
https://github.com/kerryjiang/SuperSocket.ClientEngine/commit/e13e561cafdea273983b72d0706b0fdbab152ab8

**Comment by kerryjiang** [comment]
This change has been included in this release:
https://www.nuget.org/packages/SuperSocket.ClientEngine/0.8.0.11
