### ISSUE TITLE
超过包设定大小，断开连接未清除缓存

### ISSUE THREAD

**Issue by ourplan9000** [kerryjiang/SuperSocket.ClientEngine#67]
##  if (m_MaxPackageLength > 0)
                {
                    var length = receiveCache.Total;

                    if (length > m_MaxPackageLength)
                    {
                       **m_ReceiveCache.Clear();**
                        return ProcessResult.Create(ProcessState.Error, string.Format("Max package length: {0}, current processed length: {1}", m_MaxPackageLength, length));
                    }
                }

**Comment by ourplan9000** [comment]
原文未添加 m_ReceiveCache.Clear();

**Comment by kerryjiang** [comment]
I did a fix just now. Could you check if it works?

https://github.com/kerryjiang/SuperSocket.ClientEngine/commit/abd8140aed1ecdfec12cb18023dd4e6ee934c5b2

**Comment by kerryjiang** [comment]
Already pushed to nuget, just use the version 0.8.0.11
https://www.nuget.org/packages/SuperSocket.ClientEngine/0.8.0.11

**Comment by ourplan9000** [comment]
08.0.11确实可以了， 但.net 4.5使用await关键无法连127.0.0.1以上外的IP

**Comment by kerryjiang** [comment]
你代码咋写的？

**Comment by ourplan9000** [comment]
client = new EasyClient<StringPackageInfo>();
            var fakeReceiveFilter = new FakeReceiveFilter();
    client.Initialize(fakeReceiveFilter);
            var ipAddress = IPAddress.Parse("127.0.0.1");
    var ipEndPoint = new IPEndPoint(ipAddress, 9090);
    // client.LocalEndPoint = ipEndPoint;

    client.NewPackageReceived += client_NewPackageReceived;
            client.Error += client_Error; 
            client.Connected += client_Connected;
            client.Closed += client_Closed;
            await client.ConnectAsync(ipEndPoint);
    public class EasyClient<TPackageInfo> : EasyClientBase
      where TPackageInfo : IPackageInfo
    {
        public event EventHandler<PackageEventArgs<TPackageInfo>> NewPackageReceived; 
        public EasyClient()
        {

        } 
        public virtual void Initialize(IReceiveFilter<TPackageInfo> receiveFilter)
        {
            PipeLineProcessor = new DefaultPipelineProcessor<TPackageInfo>(receiveFilter,
                2 * 1024 * 1024);
        } 
        protected override void HandlePackage(IPackageInfo package)
        {
            var handler = NewPackageReceived;

            if (handler == null)
                return;

            handler(this, new PackageEventArgs<TPackageInfo>((TPackageInfo)package));
        }
        /// <summary>
        /// 析构函数释放连接
        /// </summary>
        ~EasyClient()
        {
            if (this.IsConnected)
                this.Close();
        }
    }
}

**Comment by kerryjiang** [comment]
是不是被UI线程锁住了？ await client.ConnectAsync(ipEndPoint).ConfigureAwait(false);

**Comment by ourplan9000** [comment]
用你提供的代码也不行，不用await也不行

**Comment by ourplan9000** [comment]
反正127.0.0.1以外的ip连不了

**Comment by ourplan9000** [comment]
换成4.0的就可以
