### ISSUE TITLE
.Net 4.0 无法编译

### ISSUE THREAD

**Issue by yangmijun** [kerryjiang/SuperSocket.ClientEngine#68]
在.Net 4.0版本加入包后client.ConnectAsync编译不通过，报告 预定义类型“System.Runtime.CompilerServices.AsyncTaskMethodBuilder”未定义或未载入，将工程改为.Net 4.5 后问题消失，作者能否提供一下 .Net 4.0下的使用说明或者DEMO？

**Comment by kerryjiang** [comment]
你用的什么版本？

**Comment by yangmijun** [comment]
搞清楚问题了，原来是因为示例程序里有 async ，而.net 4.0不支持，必须在工程中再添加包 Microsoft.Bcl.Async，然后就能编译通过了，所以对于 .net 4.0来说，实际上 Microsoft.Bcl.Async是一个依赖项。

**Comment by kerryjiang** [comment]
.NET 4.0的项目引用 .NET 4.0的 SuperSocket.ClientEngine就行了。
