### ISSUE TITLE
No way to ignore RemoteCertificateChainErrors

### ISSUE THREAD

**Issue by blackspherefollower** [kerryjiang/SuperSocket.ClientEngine#78]
I'm trying connect to a WebSocket server with WebSocket4Net, and I'm finding that the server is only including the first certificate, not the full chain (a different issue that I'll be chasing elsewhere). The problem is that this is failing to pass the checks in Core/SslStreamTcpSession.cs with both Allow* flags set to true.

Would it be possible to add a 3rd option of Security.AllowNameBadChain?

In the meantime, I'll have to fall back to setting the ServicePointManager.ServerCertificateValidationCallback myself, but I don't really want to do this on a global scope, just for this one connection (unless there's a way to matching the sender to the WebSocket object?)

**Comment by kerryjiang** [comment]
It is doable. :)
If you can send a PR, that would accelerate the enhancement.

**Comment by kerryjiang** [comment]
WebSocket4Net 0.15.1
https://www.nuget.org/packages/WebSocket4Net/0.15.1

A new security option RemoteCertificateChainErrors was added.

**Comment by blackspherefollower** [comment]
Thanks @kerryjiang. It's most appreciated
