### ISSUE TITLE
EasyClient Unhandled Exception

### ISSUE THREAD

**Issue by chinason** [kerryjiang/SuperSocket.ClientEngine#82]
今天在测试断网后程序能否恢复网络时，EasyClient 出现如下异常。EasyClient版本为0.8.0.14。
Unhandled Exception: System.InvalidOperationException: 在已经完成任务后，尝试将任务转换为最终状态。
   在 System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
   在 SuperSocket.ClientEngine.EasyClientBase.FinishConnectTask(Boolean result)
   在 SuperSocket.ClientEngine.EasyClientBase.OnSessionError(Object sender, ErrorEventArgs e)
   在 SuperSocket.ClientEngine.AsyncTcpSession.ProcessReceive(SocketAsyncEventArgs e)
   在 System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   在 System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   在 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

**Comment by kerryjiang** [comment]
你好，你又能够重现这个异常的测试代码吗？

**Comment by chinason** [comment]
附件是部分代码。





--

i'm chinason

在 2017-12-21 15:21:54，"Kerry Jiang" <notifications@github.com> 写道：


你好，你又能够重现这个异常的测试代码吗？

**Comment by chinason** [comment]
[code-snippet.txt](https://github.com/kerryjiang/SuperSocket.ClientEngine/files/1578458/code-snippet.txt)

使用EasyClient的代码片段

**Comment by chinason** [comment]
![socket-exception](https://user-images.githubusercontent.com/1896647/34249043-2d47ecec-e673-11e7-9437-4c0bb02ca802.png)
这是我在windows 2012(虚拟机)测试截图。通过断开虚拟机网络的方式模拟断网情形。

**Comment by kerryjiang** [comment]
前面是已经连接成功了吗？

**Comment by kerryjiang** [comment]
貌似是不可能发生的事情啊：

`bool FinishConnectTask(bool result)
        {
            var connectTaskSource = m_ConnectTaskSource;

            if (connectTaskSource == null)
                return false;

            if (Interlocked.CompareExchange(ref m_ConnectTaskSource, null, connectTaskSource) == connectTaskSource)
            {
                connectTaskSource.SetResult(result);
                return true;
            }

            return false;
        }`

**Comment by chinason** [comment]
一开始是连接成功了，然后模拟断网，就出现了异常。

**Comment by chinason** [comment]
有 没有可能，从连接到未连接时，OnSessionClosed和OnSessionError先后执行，而那个连接m_ConnectTaskSource在连接成功时已经完成了。
ConnectAsync->m_ConnectTaskSource complete->OnSessionClosed->OnSessionError

**Comment by kerryjiang** [comment]
连接完成了 m_ConnectTaskSource 会被设成null, SetResult只会运行一次。
而且是线程安全的，我用的是Interlocked.CompareExchange.

‘
if (Interlocked.CompareExchange(ref m_ConnectTaskSource, null, connectTaskSource) == connectTaskSource)
        {
            connectTaskSource.SetResult(result);
            return true;
        }
’

**Comment by kerryjiang** [comment]
O, I probably figure out this issue.

Take a look at one change I made yesterday.

https://github.com/kerryjiang/SuperSocket.ClientEngine/commit/16bb7b52ba19bbb20f10f1462087e31ed2dcf016

It should be a concurrent issue.

m_ConnectTaskSource was cleared but later it was assigned again with the finished task completion source.

**Comment by chinason** [comment]
Great! Thanks!

**Comment by kerryjiang** [comment]
Please get the 0.10:
https://www.nuget.org/packages/SuperSocket.ClientEngine/0.10.0

**Comment by chinason** [comment]
en. tested, it fixed!
