### ISSUE TITLE
断线自动重连

### ISSUE THREAD

**Issue by chengwengao** [kerryjiang/SuperSocket.ClientEngine#85]
我已经把作者的supersocket服务端用于生产环境，但是现在有个场景需要把supsocket服务端接收到的原始数据转发一份到另外一台服务器，要求与转发服务器失去连接时能自动重连，并且保证尽可能少的丢包，不知道作者的SuperSocket.ClientEngine框架是否提供了断线自动重连机制？

**Comment by kerryjiang** [comment]
重连需要自己控制。

**Comment by chengwengao** [comment]
好的，谢谢！
