### ISSUE TITLE
SocketOptionName.KeepAlive on iOS failing intermitently

### ISSUE THREAD

**Issue by codeknox** [kerryjiang/SuperSocket.ClientEngine#9]
Hey there,
from time to time, below line fails on iOS devices:

#if !SILVERLIGHT
            //Set keep alive
            Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.KeepAlive, true);
#endif

this is on ProcessConnect of TcpClientSession.cs.

It only happens on release mode, I've not even a single repro with DEBUG on. This is the call stack, as capture by RayGun:
```
[ArgumentException: Value does not fall within the expected range.]
    System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Boolean optionValue) in <filename unknown>:0
    SuperSocket.ClientEngine.TcpClientSession.ProcessConnect2(System.Object socket, System.Net.Sockets.SocketAsyncEventArgs e) in <filename unknown>:0
    System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs e) in <filename unknown>:0
    System.Net.Sockets.SocketAsyncEventArgs.ConnectCallback(IAsyncResult ares) in <filename unknown>:0
    System.Net.Sockets.SocketAsyncEventArgs.DispatcherCB(IAsyncResult ares) in <filename unknown>:0
    System.Net.Sockets.Socket+SocketAsyncResult.<DoMConnectCallback>m__0(System.Object _) in <filename unknown>:0
```

As for OS version, it can happen on any one and on any device, I've 742 entries, and a very spread range of OS version and devices.

I've even found something online talking about this line:
http://fastchicken.co.nz/2014/02/11/making-xamarin-ios-talk-to-meteor/

But looks like for him it was ALWAYS failing.

I've tested without it and my iOS app does NOT work.

Hope it's clear,
CodeKnox

**Comment by kerryjiang** [comment]
Hello, I have added a try/catch for that line.
